export const NotificationType = {
    BID_PLACED: 'BID_PLACED',
    BID_ACCEPTED: 'BID_ACCEPTED',
    BID_REJECTED: 'BID_REJECTED',
    BID_EXPIRED: 'BID_EXPIRED',
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_STATUS_CHANGE: 'ORDER_STATUS_CHANGE',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    PAYMENT_REMINDER: 'PAYMENT_REMINDER',
    ADMIN_BROADCAST: 'ADMIN_BROADCAST',
    FERTILIZER_ALLOCATED: 'FERTILIZER_ALLOCATED',
    FERTILIZER_READY: 'FERTILIZER_READY',
    FERTILIZER_COLLECTED: 'FERTILIZER_COLLECTED',
    FERTILIZER_EXPIRED: 'FERTILIZER_EXPIRED'
};

class NotificationService {
}

// Export a singleton instance
export const notificationService = new NotificationService();